project:
  name: quickstart-microfocus-amc-es
  owner: chris.turner@microfocus.com
  shorten_stack_name: true
  s3_regional_buckets: true
  parameters:
    KeyPairName: $[taskcat_getkeypair]
  regions:
    #    - ap-northeast-1  # Asia Pacific (Tokyo)
    #    - ap-northeast-2  # Asia Pacific (Seoul)
    #    - ap-south-1      # Asia Pacific (Mumbai) --> RDS-WinAuth not supported 2019-01-01
    - ap-southeast-1  # Asia Pacific (Singapore)
    #    - ap-southeast-2  # Asia Pacific (Sydney) --> Skipped since m5/c5.large not available in ap-southeast-2a)
    - ca-central-1    # Canada (Central)
    - eu-central-1    # EU (Frankfurt)
    #    - eu-north-1      # EU (Stockholm)  --> DirSrv not supported 2019-01-01
    - eu-west-1       # EU (Ireland)
    - eu-west-2       # EU (London)
    #    - eu-west-3       # EU (Paris)  --> DirSrv not supported 2019-01-01
    #    - sa-east-1       # South America (São Paulo) --> RDS-WinAuth not supported 2019-01-01
    - us-east-1       # US East (N. Virginia)
    - us-east-2       # US East (Ohio)
    #    - us-west-1       # US West (N. California) --> RDS-WinAuth not supported 2019-01-01
    - us-west-2       # US West (Oregon)

tests:
  # Full: FS & DB (Linux)
  master-linux-fs-db:
    template: ./templates/mf-es-master-template.yaml
    parameters:
      AdditionalESStorageinGiB: "1024"
      AvailabilityZones: "$[taskcat_genaz_2]"
      DatabaseType: "Create-RDS-Remote-Database"
      DBBackupRetentionPeriod: "30"
      DBInstanceClass: "db.r4.large"
      DBMasterUsername: "DBAdmin"
      DBMasterUserPassword: "$[taskcat_genpass_12A]"
      DBMasterUserPasswordConfirm: "$[taskcat_getval_DBMasterUserPassword]"
      DBPreferredBackupWindow: ""
      DBPreferredMaintenanceWindow: ""
      DSMicrosoftADEdition: "Enterprise"
      DBStorageInGiB: "1024"
      DemoAppsIngressCIDR: "10.0.0.0/16"
      DeployMultiAZ: "false"
      DomainAdminPassword: "$[taskcat_genpass_12A]"
      DomainAdminPasswordConfirm: "$[taskcat_getval_DomainAdminPassword]"
      DomainDNSName: "example.com"
      DomainNetBIOSName: "example"
      ESCWLogGroupRetentionInDays: "7"
      ESDemoUserPassword: "Password123!"
      ESDemoUserPasswordConfirm: "$[taskcat_getval_ESDemoUserPassword]"
      ESInstanceType: "c5.large"
      ESLicenseFilename: override
      ESResourceNamePrefix: "AWS::StackName"
      FSInstanceType: "c5.large"
      FSStorageInGiB: "50"
      FileshareType: "Create-Remote-Fileshare-Server"
      FSVIEWUserPassword: "Password123!"
      FSVIEWUserPasswordConfirm: "Password123!"
      InstallFSDemoApp: "true"
      InstallSQLDemoApp: "true"
      LicenseAgreement: "I agree"
      MFDSServiceAccountName: "MFDSServiceAccount"
      MFDSServiceAccountPassword: "Password123!"
      MFDSServiceAccountPasswordConfirm: "$[taskcat_getval_MFDSServiceAccountPassword]"
      NumberOfRDGWHosts: "1"
      OperatorEmail: "None"
      PrivateSubnet1ACIDR: "10.0.0.0/19"
      PrivateSubnet2ACIDR: "10.0.32.0/19"
      PublicSubnet1CIDR: "10.0.128.0/20"
      PublicSubnet2CIDR: "10.0.144.0/20"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: "quickstart-microfocus-amc-es/"
      ESS3BucketName: override
      ESS3BucketRegion: us-east-1
      RDGWCIDR: "10.0.0.0/16"
      RDGWInstanceType: "t2.large"
      RegionsPerInstance: "1"
      NumberOfBastionHosts: "1"
      BastionInstanceType: "t2.large"
      InstallPACDemoApp: "true"
      PACDBInstanceClass: "db.r4.large"
      PACDBMasterUsername: "DBAdmin"
      PACDBMasterUserPassword: "$[taskcat_genpass_12A]"
      PACDBMasterUserPasswordConfirm: "$[taskcat_getval_PACDBMasterUserPassword]"
      OS: "Red Hat Enterprise Linux"
      BastionCIDR: "10.0.0.0/16"
      VPCCIDR: "10.0.0.0/16"
    regions:
      # - us-east-2          # US East (Ohio)          --> Windows testing below
      - us-east-1          # US East (N. Virginia)
      # - us-west-1          # US West (N. California) --> RDS-WinAuth not supported 2020-Feb-07
      - us-west-2          # US West (Oregon)
      # - ap-east-1          # Asia Pacific (Hong Kong) --> MFES not available
      # - ap-south-1         # Asia Pacific (Mumbai) --> RDS-WinAuth not supported 2020-Feb-07
      # - ap-northeast-3     # Asia Pacific (Osaka-Local) --> Osaka-Local not supported, DirSrv not supported 2020-Feb-07
      # - ap-northeast-2     # Asia Pacific (Seoul) --> Skip testing due to 'Failed to locate Availability Zone: ap-northeast-2b' issue
      - ap-southeast-1     # Asia Pacific (Singapore)
      - ap-southeast-2     # Asia Pacific (Sydney)
      - ap-northeast-1     # Asia Pacific (Tokyo)
      # - ca-central-1       # Canada (Central) Canada AMI not available.
      # - cn-north-1         # China (Beijing) --> China not supported
      # - cn-northwest-1     # China (Ningxia) --> China not supported
      - eu-central-1       # Europe (Frankfurt)
      - eu-west-1          # Europe (Ireland)
      - eu-west-2          # Europe (London)
      # - eu-west-3          # Europe (Paris) --> DirSrv not supported 2020-Feb-07
      # - eu-north-1         # Europe (Stockholm) --> RDGW required t2.x no longer available
      # - me-south-1         # Middle East (Bahrain) --> MFES not available, DirSrv not supported 2020-Feb-07
      # - sa-east-1          # South America (Sao Paulo) --> RDS-WinAuth not supported 2020-Feb-07
      # - us-gov-east-1      # AWS GovCloud (US-East) --> GovCloud not supported, RDS-WinAuth not supported 2020-Feb-07
      # - us-gov-west-1      # AWS GovCloud (US-West) --> GovCloud not supported, RDS-WinAuth not supported 2020-Feb-07

  # Full: FS & DB (Windows)
  master-windows-fs-db:
    template: ./templates/mf-es-master-template.yaml
    parameters:
      AdditionalESStorageinGiB: "1024"
      AvailabilityZones: "$[taskcat_genaz_2]"
      DatabaseType: "Create-RDS-Remote-Database"
      DBBackupRetentionPeriod: "30"
      DBInstanceClass: "db.r4.large"
      DBMasterUsername: "DBAdmin"
      DBMasterUserPassword: "$[taskcat_genpass_12A]"
      DBMasterUserPasswordConfirm: "$[taskcat_getval_DBMasterUserPassword]"
      DBPreferredBackupWindow: ""
      DBPreferredMaintenanceWindow: ""
      DSMicrosoftADEdition: "Enterprise"
      DBStorageInGiB: "1024"
      DemoAppsIngressCIDR: "10.0.0.0/16"
      DeployMultiAZ: "false"
      DomainAdminPassword: "$[taskcat_genpass_12A]"
      DomainAdminPasswordConfirm: "$[taskcat_getval_DomainAdminPassword]"
      DomainDNSName: "example.com"
      DomainNetBIOSName: "example"
      ESCWLogGroupRetentionInDays: "7"
      ESDemoUserPassword: "Password123!"
      ESDemoUserPasswordConfirm: "$[taskcat_getval_ESDemoUserPassword]"
      ESInstanceType: "c5.large"
      ESLicenseFilename: override
      ESResourceNamePrefix: "AWS::StackName"
      FSInstanceType: "c5.large"
      FSStorageInGiB: "50"
      FileshareType: "Create-Remote-Fileshare-Server"
      FSVIEWUserPassword: "Password123!"
      FSVIEWUserPasswordConfirm: "Password123!"
      InstallFSDemoApp: "true"
      InstallSQLDemoApp: "true"
      LicenseAgreement: "I agree"
      MFDSServiceAccountName: "MFDSServiceAccount"
      MFDSServiceAccountPassword: "Password123!"
      MFDSServiceAccountPasswordConfirm: "$[taskcat_getval_MFDSServiceAccountPassword]"
      NumberOfRDGWHosts: "1"
      OperatorEmail: "None"
      PrivateSubnet1ACIDR: "10.0.0.0/19"
      PrivateSubnet2ACIDR: "10.0.32.0/19"
      PublicSubnet1CIDR: "10.0.128.0/20"
      PublicSubnet2CIDR: "10.0.144.0/20"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3BucketRegion: $[taskcat_current_region]
      QSS3KeyPrefix: "quickstart-microfocus-amc-es/"
      ESS3BucketName: override
      ESS3BucketRegion: us-east-1
      RDGWCIDR: "10.0.0.0/16"
      RDGWInstanceType: "t2.large"
      RegionsPerInstance: "1"
      NumberOfBastionHosts: "1"
      BastionInstanceType: "t2.large"
      InstallPACDemoApp: "true"
      PACDBInstanceClass: "db.r4.large"
      PACDBMasterUsername: "DBAdmin"
      PACDBMasterUserPassword: "$[taskcat_genpass_12A]"
      PACDBMasterUserPasswordConfirm: "$[taskcat_getval_PACDBMasterUserPassword]"
      OS: "Windows"
      BastionCIDR: "10.0.0.0/16"
      VPCCIDR: "10.0.0.0/16"
    regions:
      - us-east-2       # US East (Ohio)
