//Include any predeployment steps here, such as signing up for a Marketplace AMI or making any changes to a partner account. If there are no predeployment steps, leave this file empty.

== Predeployment steps

The BankDemo demonstration application that is included as part of this Partner Solution requires a TN3270 terminal emulator. You can use any TN3270 terminal
emulator, but this guide covers Micro Focus Rumba, which is supplied with Micro Focus Enterprise Developer.

Before launching this Partner Solution for Enterprise Server, you must review the terms of the
https://www.microfocus.com/documentation/enterprise-developer/ed-latest/ES-WIN/GUID-0562B3C9-2271-4CE8-AF64-93DE4940077F.html[Micro
Focus End User License Agreement^]. You will be asked to accept the terms of the End User License Agreement during deployment.

=== Prepare an Amazon S3 bucket

Launch the Enterprise Server Partner Solution from an Amazon S3 bucket. These instructions guide you through the content of this bucket. The commands use AWS CLI on Windows, but if you prefer, you can use the Amazon S3 console to complete the tasks. +
If you are deploying from local files or a non-S3 location, you can skip these steps.

NOTE: Cloning the GitHub repository requires an SSH key. Generate a new SSH key pair and add the public key to your GitHub account. If you are not familiar with SSH keys in GitHub, refer to https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account[Adding a new SSH key to your GitHub account - GitHub Docs, role=external,window=_blank].

. Create a new folder for the templates and scripts, for example, *C:\quickstart-microfocus-amc-es*.
. Download the following contents and submodules from our GitHub repository, by entering the following command:

```
git clone --recursive -c core.autocrlf=false git@github.com:aws-quickstart/quickstart-microfocus-amc-es.git C:\quickstart-microfocus-amc-es
```

TIP: Check that the script files within the 'scripts' sub-folders of the cloned repository contain the correct line endings for their platform: .ps1 files should have Windows-style line endings (CRLF), and .sh files should have Linux-style line endings (LF).

[start=3]
. Upload this entire structure, excluding the GitHub metadata files (*git*) into an existing, empty S3 bucket; for example, if using the AWS command line tools on your local machine:
+
```
aws s3 cp C:\quickstart-microfocus-amc-es s3://aws-quickstart/quickstart-microfocus-amc-es/ --recursive --exclude \*git* --quiet
```
+
where _aws-quickstart_ is the name of the S3 bucket.
. Add your license file (.mflic) into a folder named *license* in the same S3 bucket; for example:
+
```
aws s3 cp .\Enterprise-Server.mflic s3://aws-quickstart/license/Enterprise-Server.mflic
```
+
where _Enterprise-Server.mflic_ is the name of the license file.

Using the example names above, these are the parameters that you should specify when deploying the Partner Solution:
|===
|Parameter | Value
|Quick Start S3 key prefix (QSS3KeyPrefix)	|quickstart-microfocus-amc-es/
|Quick Start S3 bucket name (QSS3BucketName)	|aws-quickstart
|Enterprise Server license filename (ESLicenseFilename)	|Enterprise-Server.mflic
|Quick Start S3 bucket name (ESS3BucketName)	|aws-quickstart
|===
For a full list of parameters required for deployment, refer to https://www.microfocus.com/media/documentation/micro-focus-enterprise-server-on-the-aws-cloud-deployment-guide-documentation.pdf[Micro Focus Enterprise Server on the AWS Cloud Deployment Guide^]. +
This example employs one bucket for both the Partner Solution and the Enterprise Server parameters. If required, you can employ separate buckets for each.
